@{
    ModuleVersion = '1.0'
    Author = 'euewrqe'
    Email = 'aligarcon_free@email.com'
}

function Get-Power([double]$exponent, [double]$base){
    $product = $base
    if($exponent -gt 0){
        for($i=0;$i -lt $exponent-1;$i++){
            $product *= $base
        }
    }elseif ($exponent -eq 0){
        $product = 1.0
    }else{
        throw ("occure an error, the procedure is not complete")
    }

    return $product
}



Export-ModuleMember -Function Get-Power


# performing
try{
    get-power -2 3
}catch {
    Write-Error "an error occured, caution you"
}

function test-convertTo-Html(){
    $htmlParams = @{
        Title = "Windows Services: Server01"
        Body = Get-Date
        PreContent= "<p>Generated by Corporate IT</p>"
        PostContent = "For details, contact Corporate IT."
    }
    Get-Service|
        ConvertTo-Html @htmlParams |
            Out-File Services.htm
    
    Invoke-Item Services.htm
}

# powershell#7
function test-convertTo-Html-2{
    Get-Service | ConvertTo-Html -Meta @{
        refresh=10
        author="je plaçe le bureau"
        keywords="PowerShell, HTML, ConvertTo-HTML"
    } -Charset "UTF-8"
}